### ISSUE TITLE
Heading estimation is not started because the stop calibration is not yet completed

### ISSUE THREAD

**Issue by chinitaberrio** [MapIV/hawkeye#1]
When testing with the sample data I see:

`[ WARN] [1681344439.577511850]: Heading estimation is not started because the stop calibration is not yet completed`

Is there something else I need to do?

**Comment by rsasaki0109** [comment]
The sample data is outdated and will be updated in the near future.

Eagleye, which is used for GNSS/IMU, needs to be stationary for the first 5-10 seconds. However, the current measurement system is not stationary at the beginning in the current sample data.

**Comment by rsasaki0109** [comment]
ping @screenflip
